# Generated by Django 4.1.1 on 2022-10-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1024)),
                ("status", models.CharField(max_length=1024)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
